### ISSUE TITLE
JEI lockup on three avaritia items: infinity bow, hoe, and sword

### ISSUE THREAD

**Issue by Verdigris97** [Morpheus1101/Avaritia#129]
In the latest versions of all packs I have with both JEI and Avaritia 1.1x, there seems to be a rendering problem that locks up the Minecraft client completely when JEI tries to display items in Avaritia 1.1x.  

Errors in the forge mod loader log indicate a problem locating model resources for three infinity items. (infinity_bow.json, infinity_hoe.json, infinity_sword.json)  One example:

_Exception loading model for variant avaritia:infinity_bow#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model avaritia:item/infinity_bow with loader VanillaLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:161)
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:302)
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:175)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:151)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.io.FileNotFoundException: avaritia:models/item/infinity_bow.json
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:334)
	at net.minecraftforge.client.model.ModelLoader.access$1400(ModelLoader.java:115)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:861)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:157)
	... 14 more_

There is a similar error immediately after this one for the VariantLoader, too.

I have not modified the packs at all, I'm using the pack-defined versions of forge, and my Java and graphics drivers are completely up to date.  I am running Windows 7 on a laptop (Lenovo P50) with 8 cores and PLENTY of memory. (32GB, but set to 8192 MB for Minecraft)

Symptom: The game freezes in place when JEI tries to render some items from Avaritia 1.1x, and will not resume.  This might be from opening a chest, searching JEI from inventory, etc.  There is no crash report or error log generated because Minecraft doesn't crash, it just hangs.

Steps to reproduce: Launch the pack, (e.g., Enigmatica 2 Expert) then, once everything settles down, open the inventory, and in the JEI search bar try to search for items from the avaritia mod: '@av'.  Minecraft will completely freeze before the letter 'v' even renders.  I have done this at least 20 times with each modpack, trying to determine the root cause of the problem.  Other searches also yield a frozen client as soon as they would pull one of those three items onto the screen.

Additional Evidence: In Enigmatica 2 Expert and Enigmatica 2 Expert Skyblock, I cannot view the "Bragging Rights" page in the quest book.  If I try, the client locks up.  This page contains Avaritia item images.

Additional Evidence: removing Avaritia 1.1x from the list of mods completely eliminates the problem.  Every other mod renders fine in JEI.

Final Evidence:  I created a custom modpack with just Avaritia 1.1x and JEI, and JEI locked up completely when I looked up the avaritia items.

Is this just me, or are other people having this problem?  I've seen a few people complaining about unexplained crashes in these packs, but they either generate crash reports or they don't provide enough information to determine if this is the same problem.

**Comment by Morpheus1101** [comment]
Im able to load multiple packs with JEI & Avaritia in it an able to view all Avaritia items and recipes without issue.

**Comment by Verdigris97** [comment]
Could Windows 7 cause a problem with java locating the resources?  (Are you able to test on Windows 7?)

**Comment by Morpheus1101** [comment]
I have no means in which to test this on Win7

**Comment by covers1624** [comment]
This is just a model loading error, that has nothing to do with JEI hanging.

**Comment by WindFox** [comment]
It's not Windows 7. I have this issue on my laptop that run Win 10. I'm thinking it's a GPU issue.

**Comment by Draxhax** [comment]
I'm running into this issue as well on one of my machines. None of my others run into the issue. It took me quite a while to narrow down that it was a freeze with JEI rendering avaritia items as it never actually crashed, just hung and never recovered.

I noticed that the model of laptop that Verdigris97 is using has an Nvidia Quadro (M1000M) card in it. The system I am having the issue with is also using a Quadro (P5000) card. @WindFox -- is the system you're having an issue on also using a Quadro card?

**Comment by WindFox** [comment]
HP Elitebook 8570w with a Quadro K1000M.

**Comment by Draxhax** [comment]
I'm not certain when it might have been fixed. The driver my quadro was using when I was getting the hang was 411.95, which was admittedly old.

I updated it to 436.30 (today's release (9/10/2019)) and the hang didn't happen. I don't know which driver update might have fixed the issue along the way, but at least as of today's driver, I'm not getting the hang while trying to render the stuff. =)

**Comment by WindFox** [comment]
Just updated to 426 from 425.31 and it was fixed for me. Finally, I can use Avarita on my lappy.
